<?php
/**
 * Created by PhpStorm.
 * User: chiragpatel
 * Date: 10/4/17
 * Time: 3:34 PM
 */

namespace Atyantik\Mozscape\Constants;


class ApiConstant
{
    const ANCHOR_SCOPE_PHRASE_TO_PAGE = 'phrase_to_page';
    const ANCHOR_SCOPE_PHRASE_TO_SUBDOMAIN = 'phrase_to_subdomain';
    const ANCHOR_SCOPE_PHRASE_TO_DOMAIN = 'phrase_to_domain';
    const ANCHOR_SCOPE_TERM_TO_PAGE = 'term_to_page';
    const ANCHOR_SCOPE_TERM_TO_SUBDOMAIN = 'term_to_subdomain';
    const ANCHOR_SCOPE_TERM_TO_DOMAIN = 'term_to_domain';
    const ANCHOR_SORT_DOMAINS_LINKING_PAGE = 'domains_linking_page';
    const ANCHOR_COL_TERM_OR_PHRASE = 2;
    const ANCHOR_COL_INTERNAL_PAGES_LINK = 8;
    const ANCHOR_COL_INTERNAL_SUBDMNS_LINK = 16;
    const ANCHOR_COL_EXTERNAL_PAGES_LINK = 32;
    const ANCHOR_COL_EXTERNAL_SUBDMNS_LINK = 64;
    const ANCHOR_COL_EXTERNAL_ROOTDMNS_LINK = 128;
    const ANCHOR_COL_INTERNAL_MOZRANK = 256;
    const ANCHOR_COL_EXTERNAL_MOZRANK = 512;
    const ANCHOR_COL_FLAGS = 1024;
    const LINKS_SCOPE_PAGE_TO_PAGE = 'page_to_page';
    const LINKS_SCOPE_PAGE_TO_SUBDOMAIN = 'page_to_subdomain';
    const LINKS_SCOPE_PAGE_TO_DOMAIN = 'page_to_domain';
    const LINKS_SCOPE_DOMAIN_TO_PAGE = 'domain_to_page';
    const LINKS_SCOPE_DOMAIN_TO_SUBDOMAIN = 'domain_to_subdomain';
    const LINKS_SCOPE_DOMAIN_TO_DOMAIN = 'domain_to_domain';
    const LINKS_SORT_PAGE_AUTHORITY = 'page_authority';
    const LINKS_SORT_DOMAIN_AUTHORITY = 'domain_authority';
    const LINKS_SORT_DOMAINS_LINKING_DOMAIN = 'domains_linking_domain';
    const LINKS_SORT_DOMAINS_LINKING_PAGE = 'domains_linking_page';
    const LINKS_FILTER_INTERNAL = 'internal';
    const LINKS_FILTER_EXTERNAL = 'external';
    const LINKS_FILTER_NOFOLLOW = 'nofollow';
    const LINKS_FILTER_FOLLOW = 'follow';
    const LINKS_FILTER_301 = '301';
    const LINKS_COL_URL = 0;
    const LINKS_COL_FLAGS = 2;
    const LINKS_COL_ANCHOR_TEXT = 4;
    const LINKS_COL_NRML_ANCHOR_TEXT = 8;
    const LINKS_COL_MOZRANK_PASSED = 16;
    const METADATA_LAST_UPDATE = 'last_update';
    const METADATA_NEXT_UPDATE = 'next_update';
    const TOPPAGES_COL_TITLE = 1;
    const TOPPAGES_COL_URL = 4;
    const TOPPAGES_COL_SUBDOMAIN = 8;
    const TOPPAGES_COL_ROOT_DOMAIN = 16;
    const TOPPAGES_COL_EXTERNAL_LINKS = 32;
    const TOPPAGES_COL_SUBDMN_EXTERNAL_LINKS = 64;
    const TOPPAGES_COL_ROOTDMN_EXTERNAL_LINKS = 128;
    const TOPPAGES_COL_JUICE_PASSING_LINKS = 256;
    const TOPPAGES_COL_SUBDMN_LINKS = 512;
    const TOPPAGES_COL_ROOTDMN_LINKS = 1024;
    const TOPPAGES_COL_LINKS = 2048;
    const TOPPAGES_COL_SUBDMN_SUBDMN_LINKS = 4096;
    const TOPPAGES_COL_ROOTDMN_ROOTDMN_LINKS = 8192;
    const TOPPAGES_COL_MOZRANK = 16384;
    const TOPPAGES_COL_SUBDMN_MOZRANK = 32768;
    const TOPPAGES_COL_ROOTDMN_MOZRANK = 65536;
    const TOPPAGES_COL_MOZTRUST = 131072;
    const TOPPAGES_COL_SUBDMN_MOZTRUST = 262144;
    const TOPPAGES_COL_ROOTDMN_MOZTRUST = 524288;
    const TOPPAGES_COL_EXTERNAL_MOZRANK = 1048576;
    const TOPPAGES_COL_SUBDMN_EXTERNALDMN_JUICE = 2097152;
    const TOPPAGES_COL_ROOTDMN_EXTERNALDMN_JUICE = 4194304;
    const TOPPAGES_COL_SUBDMN_DOMAIN_JUICE = 8388608;
    const TOPPAGES_COL_ROOTDMN_DOMAIN_JUICE = 16777216;
    const TOPPAGES_COL_CANONICAL_URL = 268435456;
    const TOPPAGES_COL_HTTP_STATUS_CODE = 536870912;
    const TOPPAGES_COL_LINKS_TO_SUBDMN = 4294967296;
    const TOPPAGES_COL_LINKS_TO_ROOTDMN = 8589934592;
    const TOPPAGES_COL_ROOTDMN_LINKS_SUBDMN = 17179869184;
    const TOPPAGES_COL_PAGE_AUTHORITY = 34359738368;
    const TOPPAGES_COL_DOMAIN_AUTHORITY = 68719476736;
    const TOPPAGES_COL_ALL = 133982846973;
    const URLMETRICS_COL_TITLE = 1;
    const URLMETRICS_COL_URL = 4;
    const URLMETRICS_COL_SUBDOMAIN = 8;
    const URLMETRICS_COL_ROOT_DOMAIN = 16;
    const URLMETRICS_COL_EXTERNAL_LINKS = 32;
    const URLMETRICS_COL_SUBDMN_EXTERNAL_LINKS = 64;
    const URLMETRICS_COL_ROOTDMN_EXTERNAL_LINKS = 128;
    const URLMETRICS_COL_JUICE_PASSING_LINKS = 256;
    const URLMETRICS_COL_SUBDMN_LINKS = 512;
    const URLMETRICS_COL_ROOTDMN_LINKS = 1024;
    const URLMETRICS_COL_LINKS = 2048;
    const URLMETRICS_COL_SUBDMN_SUBDMN_LINKS = 4096;
    const URLMETRICS_COL_ROOTDMN_ROOTDMN_LINKS = 8192;
    const URLMETRICS_COL_MOZRANK = 16384;
    const URLMETRICS_COL_SUBDMN_MOZRANK = 32768;
    const URLMETRICS_COL_ROOTDMN_MOZRANK = 65536;
    const URLMETRICS_COL_MOZTRUST = 131072;
    const URLMETRICS_COL_SUBDMN_MOZTRUST = 262144;
    const URLMETRICS_COL_ROOTDMN_MOZTRUST = 524288;
    const URLMETRICS_COL_EXTERNAL_MOZRANK = 1048576;
    const URLMETRICS_COL_SUBDMN_EXTERNALDMN_JUICE = 2097152;
    const URLMETRICS_COL_ROOTDMN_EXTERNALDMN_JUICE = 4194304;
    const URLMETRICS_COL_SUBDMN_DOMAIN_JUICE = 8388608;
    const URLMETRICS_COL_ROOTDMN_DOMAIN_JUICE = 16777216;
    const URLMETRICS_COL_CANONICAL_URL = 268435456;
    const URLMETRICS_COL_HTTP_STATUS_CODE = 536870912;
    const URLMETRICS_COL_LINKS_TO_SUBDMN = 4294967296;
    const URLMETRICS_COL_LINKS_TO_ROOTDMN = 8589934592;
    const URLMETRICS_COL_ROOTDMN_LINKS_SUBDMN = 17179869184;
    const URLMETRICS_COL_PAGE_AUTHORITY = 34359738368;
    const URLMETRICS_COL_DOMAIN_AUTHORITY = 68719476736;
    const URLMETRICS_COL_ALL = 133982846973;

    // URL, PageAuthority, DomainAuthority
    const URLMETRICS_COL_DEFAULT = 103079215108;
}